version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore TestDeployOnAWS/TestDeployOnAWS.csproj
  build:
    commands:
      - dotnet build TestDeployOnAWS/TestDeployOnAWS.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ TestDeployOnAWS/TestDeployOnAWS.csproj
artifacts:
  files:
    - '**/*'